version: '2.1'
services:
     elasticsearch:
       image: elasticsearch:6.5.4
       container_name: elasticsearch
       volumes:
           - data01:/usr/share/elasticsearch/data
       networks:
           docker-elk:
       ports:
           - 9200:9200

     kibana:
       image: kibana:6.5.4
       container_name: kibana
       environment:
           - "ELASTICSEARCH_URL=http://elasticsearch:9200"
       networks:
           - docker-elk
       ports:
           - 5601:5601
       depends_on:
           - elasticsearch
    
volumes:
    data01:
        driver: local
networks:
    docker-elk:
        driver: bridge
